name: Docker CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Get short Git commit hash and set image tags
      id: image_tags
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_TAG=$(date +%s)
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Build the Docker image
      run: |
        COMMIT_HASH=${{ steps.image_tags.outputs.commit_hash }}
        IMAGE_TAG=${{ steps.image_tags.outputs.image_tag }}
        docker build . --file Dockerfile \
          --tag maheshrijal/file2md:$IMAGE_TAG \
          --tag maheshrijal/file2md:$COMMIT_HASH \
          --tag maheshrijal/file2md:latest
    
    - name: Push the Docker image to Docker Hub
      run: |
        COMMIT_HASH=${{ steps.image_tags.outputs.commit_hash }}
        IMAGE_TAG=${{ steps.image_tags.outputs.image_tag }}
        docker push maheshrijal/file2md:$IMAGE_TAG
        docker push maheshrijal/file2md:$COMMIT_HASH
        docker push maheshrijal/file2md:latest